#!/bin/bash

echo Generando las clases de java:

javac cliente/MainCliente.java
javac server/ServidorCentral.java
javac server/ServidorHilo.java
javac server/ServidorHoroscopo.java
javac server/ServidorPronostico.java

echo Ejecutando ServidorCentral

java server/ServidorCentral